# Generated by Django 6.0.4 on 2026-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='duration_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
