# Generated by Django 6.0.4 on 2026-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activitysession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
