# Generated by Django 6.0.4 on 2026-04-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
