# Generated by Django 6.0.4 on 2026-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
