# Generated by Django 4.2.29 on 2026-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_activitylog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='activitysession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
