# Generated by Django 6.0.4 on 2026-04-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activitylog_id_alter_activitysession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='activitysession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.activitysession'),
        ),
        migrations.AlterField(
            model_name='activitysession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='TabState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(db_index=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_states', to='core.activitysession')),
            ],
            options={
                'ordering': ['-entered_at'],
                'indexes': [models.Index(fields=['session', 'tab_id'], name='core_tabsta_session_f96270_idx')],
                'unique_together': {('session', 'tab_id')},
            },
        ),
    ]
