# Generated by Django 6.0.4 on 2026-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
